[package]
name = "sauce"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
libxdo = "0.6.0"
libxdo-sys = "0.11.0"
mouse-rs = "0.4.2"
rocket = "0.5.1"
tokio = "1.42.0"
ws = { package = "rocket_ws", version = "0.1.1" }
